# Docker Compose for Testing Environment
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: engine_monitoring_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"  # Different port for testing
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    tmpfs:
      - /var/lib/postgresql/data  # Use tmpfs for faster tests

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"  # Different port for testing
    command: redis-server --appendonly no  # Disable persistence for tests

volumes:
  postgres_test_data:
